apiVersion: v1
kind: Service
metadata:
  namespace: demo-live-1
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-frontend
  name: easytravel-frontend-lb
  
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    io.kompose.service: easytravel-frontend

