apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: demo-live-1
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-backend
  name: easytravel-backend
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-backend
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Xmx300m -Djava.security.egd=file:/dev/./urandom
        - name: ET_DATABASE_LOCATION
          value: easytravel-mongodb:27017
        image: dynatrace/easytravel-backend
        name: easytravel-backend
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
status: {}
